### ISSUE TITLE
[BUG] UI Redraw causing missed clicks in printer page

### ISSUE THREAD

**Issue by Soukas** [NotExpectedYet/OctoFarm#102]
In the Panel layout, there seems to be a blip every second or so, It is most obvious if you try to highlight any text in the screen.
This only occurs in the highlighted panel space in the attached photo.

![image](https://user-images.githubusercontent.com/7150686/90969963-ff8b4500-e4cc-11ea-880b-ffad7b655008.png)

This redraw event causes some mouse click events to get ignored. As a result Multiple presses of the print button are sometimes required to action a print job via this screen.

**Comment by Soukas** [comment]
Further testing, I removed all camera feeds and it was still happening significantly.

Turns out its the Nozzle and Bed temp values updating.
During the value update window the buttons within the frame no longer respond to click.
I have 5 printers running, with 6 nozzles and 5 beds worth of data I am having to click 4 times before print is registered.
I believe this issue will become more prevalent with scaling. 

Current work around is to only call prints from the List Panel, as the data field refresh loop doesn't interact with button click events in this panel.

**Comment by NotExpectedYet** [comment]
That's due to cache after looking into it. The browser shouldn't be caching the server side events, I'll put something in place to stop that. 

Regarding the other I haven't been able to reproduce with 70 printers, and 10+ printing but I have some stuff I can implment so it shouldn't be a problem regardless.

**Comment by NotExpectedYet** [comment]
![image](https://user-images.githubusercontent.com/61137988/91004184-655df680-e5cb-11ea-9982-f647398b218c.png)
What are those errors in the console?

**Comment by NotExpectedYet** [comment]
Think this is also related to how the panels jump about with the sorting enabled.

**Comment by NotExpectedYet** [comment]
I'm going to put a fix out for this and some other bugs this weekend.

**Comment by NotExpectedYet** [comment]
@Soukas I have more information on the loggin in from web interface and OctoFarm at the same time loggin out. I've spoken to the OctoPrint dev and she doesn't think it's my method of loggin in, would you mind testing your instance in safe mode too see if that's the case?
