### ISSUE TITLE
One printer keeps flashing offline/online

### ISSUE THREAD

**Issue by napter** [NotExpectedYet/OctoFarm#104]
I added a few printers, all seem fine except for one - it keeps switching between online and offline like so:
![image](https://user-images.githubusercontent.com/6260841/91760787-f459a880-eba1-11ea-828e-30e7814f501d.png)

Any idea what I can do to resolve it -or how I can troubleshoot it? The octoprint website and service seem fine.

**Comment by NotExpectedYet** [comment]
Usual checks are is CORS activated and are you using the correct api key. 

The release notes have details about recent changes in OctoPrint if this version is 1.4.1+ and OctoFarm can now only connect over Application or User API Keys not the global one. 

Older versions should still work with the global key.

**Comment by NotExpectedYet** [comment]
Hello this has been open for some time now with no response. I gather the original issue has been resolved so I'm going to close. If this isn't the case please feel free to re-open. Thanks!
