### ISSUE TITLE
[FEATURE REQUEST] Support DuetWebControl

### ISSUE THREAD

**Issue by HerrDings** [NotExpectedYet/OctoFarm#114]
**Is your feature request related to a problem? Please describe.**
Octoprint has some general disadvantages compared to print control servers which run directly on the printer main board like [DuetWebControl](https://github.com/Duet3D/DuetWebControl) ("DWC"). Thus I would like to use DWC instead of Octoprint for those of my printers supporting it. Yes, there is [something like octofarm for DWC](https://github.com/DanalEstes/MultiDuetWebMonitor), but I really like that __one__ interface to watch __all__ my printers.

**Describe the solution you'd like**
I would like Octofarm to support DWC in addition to Octoprint. Basic support (webcam, progress, stop-button) is totally sufficient.

**Describe alternatives you've considered**
* Currently I run my duet-powered printers with octoprint and go without all the DWC advantages. It works but it is not really nice.
* The other option would be to use DWC and Octoprint at the same time. That should work but gives maintenance overhead and multiple ways to control the printer (and with this multiple ways to mess up setup and prints).

**Comment by NotExpectedYet** [comment]
Currently OctoPrint is pretty baked into the system. Originally I'd only planned to include OctoPrint interfaces in the scope of this application and considering it's coded in my spare time currently I don't think this will be quick. 

Whilst I can understand the requirement and I'm looking at moving away from that dependency at a later date but there are no formal plans yet.
