### ISSUE TITLE
[FEATURE REQUEST] Job Queues

### ISSUE THREAD

**Issue by NotExpectedYet** [NotExpectedYet/OctoFarm#161]
Allow the creation/managing of Job Queues in OctoFarm. 

Use cases can be:
1. Bulk start a single file to a selection of printers.
2. Monitor the printing of multiple files to single/group of printers and automatically load the next file to start.

**Comment by simoncrabbuk** [comment]
Very keen to see job queues in OctoFarm.  I need the ability to say "print N of these files on printer group X".  I need to be able to do that for numerous files, and then be able to prioritise the resulting queue.
