### ISSUE TITLE
Could not Establish API Connection:

### ISSUE THREAD

**Issue by bcrazycramer** [NotExpectedYet/OctoFarm#170]
Yesterday I was running a version of OctoPrint pre version 1.4.2. I had a connection to OctoFarm. This morning there was an update for OctoPrint for Version 1.4.2. I updated to this version and now I'm getting these error logs in OctoFarm:

 10:48:1 | http://192.168.3.51 | Could not Establish API Connection: 403http://192.168.3.51

I have nuked the printer but I'm still getting these connection logs even through there isn't a printer listed under Printers. 

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 14]
 - OctoFarm Version [e.g. 1.1.5.7]
 - OctoPrint Version [e.g. 1.4.2]
 - OctoPrint Plugins None  yet
- MongoDB Version 3.6.8

This is a fresh turn up of OctoFarm on a Raspberry Pi4 running Ubuntu 20.04.1 

I did login to OctoPrint and generate a API key for OctoFarm. I copied this to add the printer but when I try to add the printer nothing seems to be happening. I just tried to Nuke Printers but it still has the printer somewhere. I also tested Nuke Filament and it works. 
[OctoFarm-API.log](https://github.com/NotExpectedYet/OctoFarm/files/5314012/OctoFarm-API.log)
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/5314013/OctoFarm-State.log)

**Comment by NotExpectedYet** [comment]
Just closing aha.
