### ISSUE TITLE
[FEATURE REQUEST] Support for TSD and Plugin Management

### ISSUE THREAD

**Issue by YoloPigeon** [NotExpectedYet/OctoFarm#184]
I currently run a farm of 9 printers and use the spaghetti detective which is an Ai print failure Detection Service and integration with Octo farm would make the most efficient and manageable system, Also support for managing octoprint plugins from octofarm could save a lot of time going into each printer and managing the plugins there.

**Comment by NotExpectedYet** [comment]
Closing in favour of #206 please continue discussions there.
