### ISSUE TITLE
[BUG] Adding printers that use different ports on same IP bug

### ISSUE THREAD

**Issue by ihateu3** [NotExpectedYet/OctoFarm#193]
**Describe the bug**

If I have 4 printers on a single pi, using the same IP but different ports, I am unable to add the printer using the main IP, if the ones that are using ports have already been added.

For example, if I have already added a printer on "192.168.86.59:5001", it will still allow me to add more printers with different ports, such as "192.168.86.59:5002", however, it will not allow me to add "192.168.86.59" after the previous ones have already been added, it will return an error of "Printer URL: http://192.168.86.59 already exists on farm"

This means that you first need to add "192.168.86.59", and then you can add the remainders on other ports.

**Comment by NotExpectedYet** [comment]
Define port 80 on your initial instance will get around that for now.
