### ISSUE TITLE
Missing GCode File

### ISSUE THREAD

**Issue by botbuilder1** [NotExpectedYet/OctoFarm#195]
Just set up OF 1.1.6 on a RPI 4.  Connected to my first two open printers, each with OP 1.5.2.

On one of the printers, the file list on OF was missing one of my most recent GCODE files that I have been printing.  I can start the print job on the OP console, but it still does not show up on the OF file list even when type the file name in the filter:

![image](https://user-images.githubusercontent.com/6537422/103307488-2e1aae80-49de-11eb-9e44-f3197d588073.png)

**Comment by ihateu3** [comment]
Did you click "Re-Sync"?

**Comment by NotExpectedYet** [comment]
Could you please not delete the issue template and fill it out correctly and I will help you with the issue.

**Comment by botbuilder1** [comment]
Its there now after a "ReSync"
