### ISSUE TITLE
[BUG] System settings failing to save defaults on start up 

### ISSUE THREAD

**Issue by rowanook** [NotExpectedYet/OctoFarm#198]
Hi there,
Sorry it's me again. not sure if i'm experiencing a bug, or if i've poorly set up your software. I've run a half dozen prints through Octofarm today, absolutely flawlessly, i'm loving the interface and all the data it can provide. Only problem i have so far is that, with the exception of my first print, nothing has been added into the print history. The first print, test print for some new PETG appeared in history, i could even comment notes for tweaking settings etc, Brilliant! Subsequent prints haven't. I've had a look in the history collection log, all of the remaining prints have log entries like this:

Fri, 01 Jan 2021 21:19:35 GMT | INFO | OctoFarm-HistoryCollection.log | Completed Print triggered | data:"[object Object]http://192.168.1.248" | 
Fri, 01 Jan 2021 21:19:35 GMT | ERROR | OctoFarm-HistoryCollection.log | TypeError: Cannot read property 'onFailure' of undefined | data:"Failed to capture history for http://192.168.1.248" | 

I was wondering if it's something to do with my setup? or a bug to squish? 

**Versions**
 - node version 12.20.0
 - OctoFarm Version 1.1.6
 - OctoPrint Version 1.5.2
 - OctoPrint Plugins - one instance is using GPX plugin

**Comment by NotExpectedYet** [comment]
Go into System -> Server Settings and press the Save button. Should allow history to capture. 

 This is a bug by the looks from missing settings. I'll take a look as they should be generated for defaults on a new install. Thanks for the report.
