### ISSUE TITLE
[DOCUMENTATION] Monolithic container could document mounting /data

### ISSUE THREAD

**Issue by Chrismettal** [NotExpectedYet/OctoFarm#200]
https://octofarm.net/installation#Docker

Using the monolithic container works great, but it looses configuration on container recreation since the database is not mounted persistently.

mounting the following volumes fixes this:
```
volumes:
- {your persistent folder}/OctoFarm/logs:/app/logs
- {your persistent folder}/OctoFarm/scripts:/scripts
- **{your persistent folder}/OctoFarm/data:/data**
```

**Comment by NotExpectedYet** [comment]
Thanks for the reminder! Been meaning to add that for a week will get it sorted.
