### ISSUE TITLE
[FEATURE REQUEST] Support for "Mariner3D" for SLA Printers. 

### ISSUE THREAD

**Issue by Hypertoken** [NotExpectedYet/OctoFarm#224]
Saw your post over at; https://github.com/luizribeiro/mariner

I've been using OctoFarm for all my FDM printers. I do realize there would be limited functionality, but this would be amazing to and my Mars Pro!  I have Mariner all setup and working... let me know if you need a bug tester.

**Comment by NotExpectedYet** [comment]
Hey dunno if you saw the note but I'm keeping feature requests in Discussions now. I've already setup one for this on #225 I've continued the discussion there.
