### ISSUE TITLE
Installed octofarm and it was working fine for a couple of hours, now it wont work[QUESTION]

### ISSUE THREAD

**Issue by sidneyns** [NotExpectedYet/OctoFarm#231]
**Please log a discussion for these going forward, thanks!**

Hello Guys. 
I am new at octofarm. 

I installed it on windows and I had it to work for a couple of hours with all my printers. 

Now I tried to connect at localhost:4000 and it wont work.  

At mongodb I have the following screen 

![image](https://user-images.githubusercontent.com/75071335/105416417-db1ccb80-5c18-11eb-9dcb-c1d569f287ec.png)

not sure why it does not work.

**Comment by sidneyns** [comment]
i got it solved..not sure why but the server went down and I had to restart it on command line

**Comment by NotExpectedYet** [comment]
Ok no worries, will close.
