### ISSUE TITLE
[FEATURE REQUEST] Multiple user Time count

### ISSUE THREAD

**Issue by julienrat** [NotExpectedYet/OctoFarm#232]
Hi ! is there a way to have a countabilization of hours printed by user ?

**Comment by NotExpectedYet** [comment]
Hi feature requests are in discussions now. There's a note on the ticket you must have deleted. 

Not currently no, the User system needs a massive overhaul. Currently it's only purpose is to lock the interface down. This will be coming in future versions but if you'd like to discuss the implementation future then please do open a discussion regarding it.
