### ISSUE TITLE
Canvas Hub Machine Info not showing

### ISSUE THREAD

**Issue by TheyCallMeZ** [NotExpectedYet/OctoFarm#24]
Occasionally (more often than not)
the print manager will show up empty

![image](https://user-images.githubusercontent.com/321143/78588053-ef1f4a00-780b-11ea-9ac6-7aa3b456ffd9.png)

but if you go to a valid machine and then back to this machine, it brings up the information for the previous machine.

**Comment by NotExpectedYet** [comment]
There's a push coming down the line shortly once I've had some confirmation the fixes work for prusa, I'm wondering if the canvas is producing a similar issue. 

Will be done as a release shortly, be sure to check and let me know :)

**Comment by NotExpectedYet** [comment]
I'm going to close this issue as I've had reports from other people with canvas hub it's working. If it isn't the case please feel free to re-open.
