### ISSUE TITLE
[BUG] System settings still not saving defaults!!

### ISSUE THREAD

**Issue by bdw1980** [NotExpectedYet/OctoFarm#243]
### To better help the developer understand your issue, please fill in the information below. Failing to do so will waste the developer and your own time in sorting the issue. Thanks!

**Describe the bug**
I have printed several prints since I recently did an install on pi4 and none of the History is showing up.

**To Reproduce**
None to Reproduce

**Expected behavior**
Should be collecting logs

**Screenshots**
![image](https://user-images.githubusercontent.com/42826779/106646463-653b2d00-6553-11eb-9f87-795980ce6481.png)

**Versions (please complete the following information):**
 - NodeJS Version [e.g. 13]
 - OctoFarm Version 1.1.9
 - OctoPrint Version 
 - OctoPrint Plugins none
[OctoFarm-API.log](https://github.com/NotExpectedYet/OctoFarm/files/5913637/OctoFarm-API.log)
[OctoFarm-FilamentManager.log](https://github.com/NotExpectedYet/OctoFarm/files/5913638/OctoFarm-FilamentManager.log)
[OctoFarm-HistoryCollection.log](https://github.com/NotExpectedYet/OctoFarm/files/5913639/OctoFarm-HistoryCollection.log)
[OctoFarm-InformationCleaning.log](https://github.com/NotExpectedYet/OctoFarm/files/5913640/OctoFarm-InformationCleaning.log)
[OctoFarm-InformationCleaning1.log](https://github.com/NotExpectedYet/OctoFarm/files/5913641/OctoFarm-InformationCleaning1.log)
[OctoFarm-InformationCleaning2.log](https://github.com/NotExpectedYet/OctoFarm/files/5913642/OctoFarm-InformationCleaning2.log)

**Additional context**

**Comment by NotExpectedYet** [comment]
Brilliant cheers man, will have a look.

**Comment by NotExpectedYet** [comment]
Save your System settings man. Sorry seems I've still got a bug there. 

Go to System, click on Server and press save should start capturing history again.

**Comment by NotExpectedYet** [comment]
I've updated the title to reflect the actual bug.
