### ISSUE TITLE
Some elements don't refresh

### ISSUE THREAD

**Issue by gmccauley** [NotExpectedYet/OctoFarm#25]
I'm not sure how often or repeatable it is but I've found that some elements don't refresh.

For example, I added the Current Operations to the camera view and the time remaining or progress doesn't update.  One of my prints finished, but it still says 91% and 22 minutes left in the Current Operations panel (what it was when I opened the page).  The page needs to be refreshed to show the updated values.

**Comment by NotExpectedYet** [comment]
Is fixed on development man, noticed myself the other day.

**Comment by NotExpectedYet** [comment]
Will be released with 1.1.5
