### ISSUE TITLE
[Feature Implementation] Update feedrate range from 10% to 300%

### ISSUE THREAD

**Issue by NotExpectedYet** [NotExpectedYet/OctoFarm#252]
In Octofarm Feed rate goes from 50% to 150%, in OctoPrint it's from 10% to 300%
Would be nice to be able to set lower and higher, when loading/unloading filament.

_Originally posted by @MTrab in https://github.com/NotExpectedYet/OctoFarm/discussions/251_

**Comment by MTrab** [comment]
Hmmmm. Still only able to set feed rate between 50% and 150%

**Comment by NotExpectedYet** [comment]
> Hmmmm. Still only able to set feed rate between 50% and 150%

This should be fixed now, sorry something went wrong compiling the client...
