### ISSUE TITLE
[Feature Implementation] Custom gcode scripts

### ISSUE THREAD

**Issue by NotExpectedYet** [NotExpectedYet/OctoFarm#253]
A nice feature would be the possibility to add and save custom g-codes

Could be for loading/unloading filaments

_Originally posted by @MTrab in https://github.com/NotExpectedYet/OctoFarm/discussions/250_

**Comment by NotExpectedYet** [comment]
Going to add a new UI button on Printer manager for editing gcode commands and then make them show up for selection on the gcode bulk command. Just thought of another handy feature too.

**Comment by MTrab** [comment]
Absolutely love it 👍
