### ISSUE TITLE
[FEATURE REQUEST] Move to headless framework with Webpack

### ISSUE THREAD

**Issue by InfoMTB3D** [NotExpectedYet/OctoFarm#268]
Proposal to move to Angular and or React based on Typescript related to but not limited to #267.
This will help build the assets better as these frameworks come with dev server (webpack) out of the box.

Currently Gulp is quite slow in DEV environment, and it does not result in optimal builds (not sure if it has tree shaking).

I can help out on this.

**Comment by NotExpectedYet** [comment]
I am removing gulp but I am keeping a custom nodejs backend. I won't be using Angular or React as I don't personally like them much. Feature requests in discussions.
