### ISSUE TITLE
[BUG] GridStack dashboard page tiles not flex-filling

### ISSUE THREAD

**Issue by davidzwa** [NotExpectedYet/OctoFarm#288]
Developer report

GridStack looking weird in new webpack version (didnt check in og dev)

![image](https://user-images.githubusercontent.com/6005355/107873941-6014a100-6eb6-11eb-8b7c-6fd616cf050b.png)

**Comment by NotExpectedYet** [comment]
Will be same everywhere I think. Noticed it myself just never registered it so thanks.

**Comment by davidzwa** [comment]
Just gotta make sure it's not my doing. Will come back with verification.

**Comment by NotExpectedYet** [comment]
> Just gotta make sure it's not my doing. Will come back with verification.

Is it the new graphs not flex filling or them all? That printer progress shouldn't be allowed to drop to that size tbh.

**Comment by davidzwa** [comment]
Not present (dragging problem was related to jQuery issues and webpack)
