### ISSUE TITLE
Full Screen Camera

### ISSUE THREAD

**Issue by gmccauley** [NotExpectedYet/OctoFarm#33]
When double clicking on the camera image from the Panel or Camera views (to show the camera stream full screen), the bottom 1/4rd of the stream is cut off.

I assume that the stream is trying to maintain aspect ration and since my monitors aren't perfect squares, the bottom section gets cut off.

I've attached some pics to help explain.

![IMG_20200413_092940](https://user-images.githubusercontent.com/11580087/79129087-322c7080-7d6a-11ea-9845-be17ba15f1c5.jpg)
![2020-04-13_9-31-13](https://user-images.githubusercontent.com/11580087/79129093-348eca80-7d6a-11ea-8ecb-e497ce6af0bd.png)

**Comment by NotExpectedYet** [comment]
Cheers for that, did wonder if it cut off 4:3 but I've none to test with. I'll have a look about maintaining aspect ratio, html is annoying for sizing by height but I'm sure I can work something out.

**Comment by gmccauley** [comment]
Confirmed Fixed in 1.1.4.9-dev-1 release

**Comment by NotExpectedYet** [comment]
Fixed in recent 1.1.5 push
