### ISSUE TITLE
Add full URL for printer IP - Multi Instance w/ haproxy 

### ISSUE THREAD

**Issue by zdesignstudio** [NotExpectedYet/OctoFarm#36]
When using HA proxy to append urls to the single PI IP address, OctoFarm doesnt allow the additional /name to be added, only IP address.

For example, instead of accessing a multi instance printer as 192.168.1.10:5000 or 5001 you can do 192.168.1.10/printer1, printer2, cr10, etc.
If haproxy is setup this way it does not allow access via port directly so you are unable to add the device in OctoFarm.

**Comment by NotExpectedYet** [comment]
feature requests are handled on the feathub page please. 

it's already been noted and requested please go add your vote there.

**Comment by zdesignstudio** [comment]
Apologies.
Didnt know that site was still used. Im guessing they are down again as I am unable to reach it.

**Comment by NotExpectedYet** [comment]
yeah I'm looking to move in due course to a better platform. 

your feature is been added for 1.1.5 though :) 

It seems to be up but there SSL isnt working currently.

**Comment by zdesignstudio** [comment]
Awesome.

Thanks for following up James.

**Comment by NotExpectedYet** [comment]
no trouble :) 

it's an often requested feature that was never in the original scope. I've re-planned the entire mechanism and I'm hoping to have that released in 2 weeks or so.

**Comment by NotExpectedYet** [comment]
https://features.octofarm.net is now live :) 

Please go add your feature requests there, thanks!
