### ISSUE TITLE
Allow hostnames instead of only IP addresses for machines

### ISSUE THREAD

**Issue by mfberry** [NotExpectedYet/OctoFarm#37]
Overall a minor problem, but I track my printers better through DNS than static IP addresses.

**Comment by NotExpectedYet** [comment]
Feature requests are done on feathub... this is already requested. Closing.

**Comment by NotExpectedYet** [comment]
I've just realised the site is still down -_-

I'm setting up an alternative platform shortly, but your request is coming in 1.1.5

**Comment by mfberry** [comment]
Thank you!

I thought I was a crazy person.

**Comment by NotExpectedYet** [comment]
No worries, I thought they were just having SSL issues but seems the service is completely down now. Nothing on there twitter page either -_- 

I have lost a lot of blumming feature requests due to that ahaha

**Comment by NotExpectedYet** [comment]
I'm just waiting for google to Auth my domain shizzle and it will be live :)

**Comment by NotExpectedYet** [comment]
https://features.octofarm.net is now live :) 


Please go add your feature requests there, thanks!
