### ISSUE TITLE
Can't add more printers at later stage.

### ISSUE THREAD

**Issue by kristapsdravnieks** [NotExpectedYet/OctoFarm#38]
I can't seem to find a way to add more octoprint instances to farm once inital setup wizzard is closed.
is there some url I could re-run setup wizzard or add another octopritn instance trough cli?

**Comment by NotExpectedYet** [comment]
Your going to have to explain that one more? 

System -> Printers will let you add more printers and OctoFarm doesn't really have a setup wizard.

**Comment by kristapsdravnieks** [comment]
![octofarm](https://user-images.githubusercontent.com/29129869/79638855-b7a38c80-817f-11ea-9c73-cbbff228b82f.JPG)

I don't see printers option under System menu

**Comment by NotExpectedYet** [comment]
You need to login as the first user you've created, not the second. The first user defaults to Admin which is the only user who can see that option.

**Comment by kristapsdravnieks** [comment]
is there any a way to reset user database?

**Comment by NotExpectedYet** [comment]
You'd have to delete that specific table and restart OctoFarm. 

You can do this with the MongoCLI with
`db.users.drop() `

users is the collection, that will save the rest of your data and make you create a new login on restart. 

The easiest way would be to export your printers, and change the db url on OctoFarm, then re-import but you'll loose any collected history.

**Comment by NotExpectedYet** [comment]
I'll make more notes about this when I write up some documentation. Been holding off as a lot is changing still going forward.

**Comment by kristapsdravnieks** [comment]
Thanks! That worked.

**Comment by NotExpectedYet** [comment]
Awesome! 

Will close :)
