### ISSUE TITLE
First row of list view doesn’t display 

### ISSUE THREAD

**Issue by jw59** [NotExpectedYet/OctoFarm#40]
iOS Safari, the first line is only showing the lower half of the line.  Both portrait and landscape. 

![C94EF700-97CC-49F2-9565-34559C50F88F](https://user-images.githubusercontent.com/12903320/80042649-97503680-84cd-11ea-9d92-550265ee4c92.jpeg)

**Comment by NotExpectedYet** [comment]
I think that's more of a general bug with how the sticky header is managed I will check on another mobile device. It isn't a focus the mobile view, especially on list view.

**Comment by NotExpectedYet** [comment]
This should be fixed on development

**Comment by NotExpectedYet** [comment]
Fixed in recent 1.1.5 push
