### ISSUE TITLE
Completion Time - Not calculated properly

### ISSUE THREAD

**Issue by cskozlowski** [NotExpectedYet/OctoFarm#44]
Remaining duration time for the print is correct, the estimated wall clock time is off by 4 hours.  This is an intermittent problem.

**Comment by NotExpectedYet** [comment]
You need to setup the timezone on your device

**Comment by cskozlowski** [comment]
I changed my timezone,  looks good.  Thanks !!!

**Comment by NotExpectedYet** [comment]
No worries! I'll make this more obvious in the installation guides that are on the wiki :)
