### ISSUE TITLE
feature: "remember me" on login

### ISSUE THREAD

**Issue by iandouglas** [NotExpectedYet/OctoFarm#48]
I use a tab suspender plugin for Chrome to pause processing on tabs I leave open after 15 minutes. When OctoFarm's tab goes to sleep and I click back on it to wake it up, I have to log in every time. It'd be nice to have a 'remember me' function on login that maintains a session cookie for some period of time like 30 days.

**Comment by NotExpectedYet** [comment]
Feature requests are logged on please, closing... 

http://features.octofarm.net/
