### ISSUE TITLE
typo in wiki

### ISSUE THREAD

**Issue by Mearman** [NotExpectedYet/OctoFarm#49]
just noticed a type in the wiki, nothing major.
on https://github.com/NotExpectedYet/OctoFarm/wiki/OctoFarm-Official-(MongoDB-Optional)
Last line of full yaml reads
``` - <your persistent folder>/OctoFarm/logs:/app/serverConfig ```
instead of
``` - <your persistent folder>/OctoFarm/logs:/app/logs ```

**Comment by NotExpectedYet** [comment]
Thanks have updated
