### ISSUE TITLE
File Manager sync issue

### ISSUE THREAD

**Issue by ID4600** [NotExpectedYet/OctoFarm#55]
After print is finished, when I press the "Print Harvested?" button nothing happens, it stays in the same state.

Running: 1.1.4-6-bugfix
OS: Win10 Pro

Happens on all available printers. Fresh install did not resolve the problem.

**Comment by NotExpectedYet** [comment]
Have you enabled CORS and restarted?

**Comment by NotExpectedYet** [comment]
On OctoPrint

**Comment by ID4600** [comment]
Okay that was a stupid thing to mis.....

Only thing that I can't fix is the syncing with the printers files, some printers do show the files, others simply don't even after uploading through octofarm, they disappear after a bit.

**Comment by NotExpectedYet** [comment]
Easy fix though. 

How many files are on them? It doesn't wait long enough if they aren't there. 

The disappearing is a new one though I think.

**Comment by ID4600** [comment]
There should be around 80 files here, maybe that's the problem? 
There are 10 folders and 57 files in the root. 
![mssing_files](https://user-images.githubusercontent.com/10940907/83149187-1ef71980-a0fa-11ea-9f16-1bacb3283263.jpg)

This one was uploaded through the interface of octofarm: 

![the missing file](https://user-images.githubusercontent.com/10940907/83149483-6ed5e080-a0fa-11ea-837b-539100910c1c.jpg)

**Comment by NotExpectedYet** [comment]
Yeah looks like the timeout isn't long enough. You can edit serverConfig/server.js in the OctoFarm folder to give it a little more time. There's two settings to change in there you can try to increase for API timeout. Should give it enough time to grab those files then.

**Comment by NotExpectedYet** [comment]
I'm gonna label this a bug and leave it here actually. It needs looking into more than just increasing the timeout.

**Comment by ID4600** [comment]
I've set serverConfig/timeout.js line 3 to "apiTimeout: 8000," seems to solve it for now!

**Comment by NotExpectedYet** [comment]
Fixed this on the development branch. Will be released soonish I hope.
