### ISSUE TITLE
Not able to control printers or upload files

### ISSUE THREAD

**Issue by ID4600** [NotExpectedYet/OctoFarm#56]
There seems to be a problem with having full control over the printer. 
I get status information, video and everything but I can not control the printer from octofarm. 
The same goes for files, uploading them and starting a new print job. 

Running: 1.1.4-6-bugfix
OS: Win10 Pro

Happens on all available printers. Fresh install did not resolve the problem.

**Comment by NotExpectedYet** [comment]
This would explain your first issues. CORS sounds like it's not enabled or your not on the same network as your OctoPrint clients. Going to close and continue the conversation over there as these issues are related.
