### ISSUE TITLE
Host State Keeps Disconnecting

### ISSUE THREAD

**Issue by Crane49** [NotExpectedYet/OctoFarm#65]
[OctoFarm-State.log](https://github.com/NotExpectedYet/OctoFarm/files/4741311/OctoFarm-State.log)
I am currently running octofram 1.1.5.5. When I add a printer it connects then imediately disconects from octofarm. When I resync, I get a connection but it immediately disconnects. I have 3 printers with all printers and OctoFarm hard wired on my network. I was previously runing OcotFarm 1.1.4.6 without issue. I run OctoFarm on RPi 4b 4gb headless on Ubuntu 20.04 server. I will try to change the intervals times to see if that is an issue??
![OctoFarm_Disocnnects](https://user-images.githubusercontent.com/54152628/83958746-617bcd00-a843-11ea-8d2f-f5e0dfd4f987.png)

Found this in the log
Sat, 06 Jun 2020 23:54:52 GMT | ERROR | OctoFarm-State.log | Error: Unexpected server response: 404 | data:"0: ws://172.31.156.20//sockjs/websocket" | 
Sat, 06 Jun 2020 23:54:52 GMT | ERROR | OctoFarm-State.log | WebSocket hard failure: 0: ws://172.31.156.20//sockjs/websocket | 
Sat, 06 Jun 2020 23:54:52 GMT | INFO | OctoFarm-State.log | WebSocketClient: Closed | data:{"0":1006} | 

Thanks,
Mike

**Comment by NotExpectedYet** [comment]
http://172.31.156.20/
Should be:
http://172.31.156.20

**Comment by Crane49** [comment]
Thank you. Everything is working!

**Comment by NotExpectedYet** [comment]
No trouble! 

Out of curiosity did you input those yourself or did it happen as part of the conversion? OctoFarm should detect the old IP's and re-write them correctly so I'll take a look if it isn't.

**Comment by Crane49** [comment]
I did do the input manaully.

**Comment by NotExpectedYet** [comment]
Sound no trouble, thanks for the reply :) 

Happy printing aha
