### ISSUE TITLE
upload loop (Vivaldi Browser)

### ISSUE THREAD

**Issue by Avatarsia** [NotExpectedYet/OctoFarm#72]
when i upload a gcode by drag n drop with the vivaldi browser into a folder created by octofarm i get the request  "would you like to print upon upload?", anyway what i press it restart the next upload, when i click yes it prepares the start and try to upload but fails - see issue cant delete or upload anythink when printer is running.

**Comment by NotExpectedYet** [comment]
Current supported browsers are Chrome and Firefox. I'd use one of those until I can look into this.

**Comment by Avatarsia** [comment]
Version 

Vivaldi | 3.0.1874.33 (Stable channel) (64-Bit)

I think the core is like chrome, no ?

**Comment by NotExpectedYet** [comment]
No idea, 

I'll double check and make sure there's nothing wrong with that specific function. Could you try and Chrome or Chromium and see if you get the same results?

**Comment by NotExpectedYet** [comment]
I'd Re-Sync as well to clear out any possible issues with the file list getting out of sync.

**Comment by NotExpectedYet** [comment]
I'm going to close this currently as Vivaldi isn't currently on the list of supported browsers. Because I'm a one man team I will be only focusing on Chrome and Firefox going forward.
