### ISSUE TITLE
thumbnail support, where do they show?

### ISSUE THREAD

**Issue by tonysurma** [NotExpectedYet/OctoFarm#76]
I just saw in release notes that it supports the thumbnails and I have been using that pretty extensively for weeks now in octoprint.

However I don't see them show up anywhere in octofarm.  Where/how should they show?  I can then debug but not sure where they should be showing.

Thanks again

**Comment by NotExpectedYet** [comment]
Are you on version 1.1.5.5? as they should just show in the file manager. 

![image](https://user-images.githubusercontent.com/61137988/85066528-0f259f00-b1a7-11ea-880d-6b6c6d5c5de0.png)

**Comment by NotExpectedYet** [comment]
Which thumbnail plugin are you using as well? Currently it's only UFP and Prusa.

**Comment by tonysurma** [comment]
looks like just 1.1.5 not 1.1.5.5, I need to set a reminder to check for new versions more often (or maybe we can get a tickler in the app?

And using Prusa.  Updating now and my apologies for not noticing version

**Comment by tonysurma** [comment]
closing this as it totally works if you are on the right version :)
