### ISSUE TITLE
Farm Utilisation - Offline Hours Calculation incorrect/unclear

### ISSUE THREAD

**Issue by Schokobecher** [NotExpectedYet/OctoFarm#77]
The **Offline Hours** within the **Farm Utilisation** are inaccurate or what they are based on is not clear to me. They keep ticking up irregularly (every 5 to 10+ seconds) even though all connected printers are either Active or Idle - **Current Status** and **Current Utilisation** statistics seem correct and don't have this issue.

A fresh install with printers added looks like this after about 2 minutes
![image](https://user-images.githubusercontent.com/1642634/85218664-871de000-b3c6-11ea-815d-03f3592b5fcb.png)

While  **Current Utilisation** looks like this:
![image](https://user-images.githubusercontent.com/1642634/85218680-ad438000-b3c6-11ea-8c7e-663c282f84d7.png)

An install left running for about 7hrs looks like this with two printers connected and online during that time. I would expect the ~65% added to **Idle Hours**, not **Offline Hours**

![image](https://user-images.githubusercontent.com/1642634/85218702-e4199600-b3c6-11ea-89ca-7171a012c284.png)
![image](https://user-images.githubusercontent.com/1642634/85218722-1d520600-b3c7-11ea-945b-1693fa279e5d.png)

**Comment by NotExpectedYet** [comment]
Cheers for that, I'll work in some improvements for the next release

**Comment by Schokobecher** [comment]
Not sure if related, but **Current Utilisation** also has gone wacky over time:

![image](https://user-images.githubusercontent.com/1642634/85320520-61d7c180-b4ed-11ea-8dee-9f98283a6b13.png)
![image](https://user-images.githubusercontent.com/1642634/85320535-69976600-b4ed-11ea-92d5-f590fdac6e69.png)

So 50% active + 1% Offline = 49% of missing (most likely idle) in the pie chart

**Comment by NotExpectedYet** [comment]
> Not sure if related, but **Current Utilisation** also has gone wacky over time:
> 
> ![image](https://user-images.githubusercontent.com/1642634/85320520-61d7c180-b4ed-11ea-8dee-9f98283a6b13.png)
> ![image](https://user-images.githubusercontent.com/1642634/85320535-69976600-b4ed-11ea-92d5-f590fdac6e69.png)
> 
> So 50% active + 1% Offline = 49% of missing (most likely idle) in the pie chart

Yeah I've just found the reason for that and I'm confused to why the issue wouldn't present itself sooner. I'm just doing some tweaks to sort all this for the next version. Will collect actual values now rather than trying to work it out taking active time from time alive.

**Comment by NotExpectedYet** [comment]
This should be resolved, looking for people to test the new RC
