### ISSUE TITLE
update from 1.1.4.6 to 1.1.5

### ISSUE THREAD

**Issue by fredddvargas** [NotExpectedYet/OctoFarm#78]
Hi, 

great software. quick question.. how can I upgrade from 1.1.4.6 to 1.1.5? is there a command for that or do I have to reinstall software? Something like...

```
git checkout HEAD -- X.json
git pull
npm install
```

Thanks in advance,

**Comment by NotExpectedYet** [comment]
Yeah that's it.  

Don't think you'll need checkout head a pull or fetch should do fine. 

You may need to re-do your db.js file as for some reason my gitignore is been ignored

Thanks as well!

**Comment by NotExpectedYet** [comment]
I'm going to close this as I believe the original question has been answered
