### ISSUE TITLE
No History yet - Sync History with 

### ISSUE THREAD

**Issue by quloquloqulo** [NotExpectedYet/OctoFarm#84]
I don't know why but my hystory is always empty reporting "No History yet Come back here when you've completed some prints."...

it would be interesting to remedy the problem if it could be synchronized with the printjobhistory plug-in and also recover old prints that octofarm has not saved

**Comment by NotExpectedYet** [comment]
Can you pass me some history logs please?

**Comment by NotExpectedYet** [comment]
And also what's the version number please?

**Comment by quloquloqulo** [comment]
[OctoFarm-HistoryCollection.log](https://github.com/NotExpectedYet/OctoFarm/files/4960052/OctoFarm-HistoryCollection.log)

**Comment by NotExpectedYet** [comment]
> [OctoFarm-HistoryCollection.log](https://github.com/NotExpectedYet/OctoFarm/files/4960052/OctoFarm-HistoryCollection.log)
> 
> Version 1.1.5.5
Thanks!

Have you setup anything in the filament manager at all? It's looking like this is a bug. 

Regarding syncing history, I've no plans too add support for that plugin but you can make a feature requests at https://features.octofarm.net and I can gauge popularity for it.

**Comment by quloquloqulo** [comment]
Thanks for your quick response. 
The filament manager was correctly set on both octoprint and octofarm. However I just disabled and re-enabled sync. We'll see if it resolves with the next print,

**Comment by NotExpectedYet** [comment]
Welcome :) 

Hmmm that's just a flag so it shouldn't do much, unless filament was selected when you actioned the disable and re-enable. 

If the spool has selected fine (ie stays there on a page refresh) you should be fine going forward. 

I'm just hoping the database hasn't gotten out of sync. 

History will trigger 10 seconds after a print so if you still don't see if, fire me the logs and I'll double check what's going on.

**Comment by NotExpectedYet** [comment]
Hello  did the issue resolve?

**Comment by quloquloqulo** [comment]
Yes. I start the prints from the octoprint web interface instead of octofarm. Could this be the problem?

**Comment by NotExpectedYet** [comment]
It shouldn't make a difference. 

I think the problem is with the filament manager plugin. I've done a lot of bug fixing around that area for the latest RC. I believe upgrading should solve your problem. It's the last RC before I push the new release currently, I just want to make sure it's continued to be stable as a lot has changed on the backend.

**Comment by NotExpectedYet** [comment]
This has been stale for some time now, please re-open if the issue is stiller persisting.
